service_name: me.techclips
default:
  memorysize: 128
  timeout: 60
alias:
  prod: prod
  stg: stg
version:
  latest: $LATEST
s3:
  bucketName: lambda.zip-files
add_function:
  role: arn:aws:iam::115107702932:role/lambda-dynamo
  runtime: nodejs14.x
  handler: index.js
  s3_key: me.techclips/sample.zip
